# spring.application.name=backend

# spring.datasource.url=jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
# spring.datasource.username=${DB_USER}
# spring.datasource.password=${DB_PASSWORD}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:products_db}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.db.enabled=true
management.health.defaults.enabled=true
management.endpoint.health.group.readiness.include=db
management.endpoint.health.group.liveness.include=ping


logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n



